baseURL = 'http://example.org/'
languageCode = "en-gb"
title = "Sunset Studios"

[params]
description = "Creative retreat in Gran Canaria for artists, songwriters and producers."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
